Repository gdsc-gvp/Machine-learning, pull requests merged in 2021-10, with the labels that each got.

#20 add notebook to titanic survivors
  Projects/titanic-survivors/data/dataset.csv
  Projects/titanic-survivors/predicting-titanic-survivors.ipynb
Labels: hacktoberfest-accepted, Hacktoberfest, approved

#21 Create weight prediction.ipynb
  Projects/Weight prediction/Weight.ipynb
Labels: Hacktoberfest, approved

#22 add notebook to diabetes diagnosis
  Projects/diabetes-diagnosis/diabetes-diagnosis.ipynb
  Projects/diabetes-diagnosis/diabetes.csv
Labels: Hacktoberfest

#25 Added Boston house price prediction
  Projects/Boston House Price Prediction/House Price Prediction.ipynb
Labels: hacktoberfest-accepted, Hacktoberfest

#27 Added Salary Prediction
  Projects/Salary Prediction/Salary Prediction.ipynb
  Projects/Salary Prediction/Salary.csv
Labels: hacktoberfest-accepted, Hacktoberfest, approved

#24 Added car price prediction
  Projects/Car-Price-Prediction/Car_price_prediction.ipynb
  Projects/Car-Price-Prediction/ford.csv
Labels: hacktoberfest-accepted, Hacktoberfest, approved

#30 Breast_cancer_detection
  Projects/Breast cancer Prediction/Breast_cancer_detection.ipynb
Labels: hacktoberfest-accepted, Hacktoberfest, approved

#34 Added Wine quality prediction
  Projects/wine_quality_prediction/Wine_Quality_Prediction.ipynb
  Projects/wine_quality_prediction/winequality.csv
Labels: Hacktoberfest

#32 Added Health Insurance Cost Prediction
  Projects/Health Insurance Cost Prediction/Health Insurance Cost Prediction.ipynb
  Projects/Health Insurance Cost Prediction/insurance.csv
Labels: Hacktoberfest
